GET http://localhost:3000/auth



####
GET http://localhost:3000/resetIdSequence


###

POST http://localhost:3000/auth/login
Content-Type:application/json

{
	"email": "rishavinmngo@gmail.com",
	"password": "123456789"
}


###

GET http://localhost:3000/users/getById


####

GET http://localhost:3000/users/getById
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjc4NjE0ODU3fQ.EQIL8d_XsFNcG-PE3pJ0bbQx5IIEL1q4zKZotwgL1oQ



###
POST http://localhost:3000/auth/register
Content-Type:application/json

{
	"name": "rishav raj",
	"email": "rishavinmngo@gmail.com",
	"password": "123456789"
}


###
GET http://localhost:3000/auth/google/logout


##
